### PR TITLE
fix: configure Spin state dir

### PR DESCRIPTION
**Pull request by kate-goldenring**
fixes https://github.com/spinkube/containerd-shim-spin/issues/216

### CODE REVIEW

**Review by Mossaka — APPROVED** [review]
lgtm, can you add this to the CHANGELOG?

**Comment by kate-goldenring** [comment]
This is also capturing logs, so we need to configure the dir for kv/sqlite but not for logs. 

```
Logging component stdio to "/.spin/logs/"
Storing default SQLite data to "/.spin/sqlite_db.db".

Serving http://0.0.0.0:80
Available Routes:
  todo-api: http://0.0.0.0:80/api (wildcard)
  fileserver: http://0.0.0.0:80 (wildcard)
```

**Comment by kate-goldenring** [comment]
Resolved logs not being displayed by explicitly unsetting the log dir. 

```sh
Storing default SQLite data to "/.spin/sqlite_db.db".

Serving http://0.0.0.0:80
Available Routes:
  todo-api: http://0.0.0.0:80/api (wildcard)
  fileserver: http://0.0.0.0:80 (wildcard)
Getting todos
Handler returned an error: Error::Io("no such table: todos")
Initializing migration
Getting todos
```

**Comment by kate-goldenring** [comment]
@Mossaka i am not sure what i would add to the CHANGLOG for this as this is a fix to ensure that we do not have a change in this release with regards to the state dir

**Pull request merged**
