### PR TITLE
feat(node-installer): #153 conditionally restart k0s controller service when present

### LINKED ISSUE #153: node-installer: k0s single node
I am new to k0s but was running through the motions of installing the shim on a local k0s cluster, thanks to the support added recently in https://github.com/spinkube/containerd-shim-spin/pull/135

I followed the k0s quickstart [here](https://docs.k0sproject.io/stable/install/) and went with the  easy-mode, `single node k0s that includes the controller and worker functions with the default configuration`

In this mode, the systemctl service is `k0scontroller` rather than `k0sworker`.  The latter is used in the node-installer logic [here](https://github.com/spinkube/containerd-shim-spin/blob/main/node-installer/script/installer.sh#L58).  Therefore, shim installation fails with the following:

```
$ k -n kwasm logs pod/lima-shimvm-provision-kwasm-nzwz6
Failed to restart k0sworker.service: Unit k0sworker.service not found.
```

Here's the systemctl service I see:
```
$ systemctl status k0sworker
Unit k0sworker.service could not be found.
$ systemctl status k0scontroller
● k0scontroller.service - k0s - Zero Friction Kubernetes
     Loaded: loaded (/etc/systemd/system/k0scontroller.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-06-28 10:56:04 MDT; 8min ago
     ...
```

Do we want to update the node-installer logic to support this single-node scenario?  Or document that a multi-node setup (i.e. with an additional worker node/systemctl service) is required?  cc @Ajpantuso

### PR DESCRIPTION
**Pull request by Ajpantuso**
### Summary

Closes #153

### CODE REVIEW

**Review by kate-goldenring — APPROVED** [review]
LGTM

**Comment by Mossaka** [comment]
Could you please sign your commit @Ajpantuso

**Review by vdice — APPROVED** [review]
Just wanted to mention that I tested this via the k0s quickstart/simple install (where svc is `k0scontroller`) and it worked great!  Thanks @Ajpantuso.

**Comment by Ajpantuso** [comment]
> Could you please sign your commit @Ajpantuso

Done

**Comment by Mossaka** [comment]
emm GitHub still doesn't show your commit as signed. 
image

**Comment by Ajpantuso** [comment]
> emm GitHub still doesn't show your commit as signed.

Fixed, gpg key had just expired.

**Pull request merged**
